algoritmo "OperaçõesBASICAS"

var
opcao : inteiro
inicio
// Seção de Comandos 
enquanto opcao <> 9 faca
escreval("Informe a operação desejada")
escreval("1-Soma")
escreval("2-Subtracao")
escreval("3-Divisão")
escreval("4-Multiplicação")
escreval("9-Sair")
leia(opcao)
escolha(opcao)
caso 1
caso 2
caso 3
caso 4
caso 9
escreval("Finalizado com sucesso")
fimescolha
fimenquanto
fimalgoritmo
